version: '3'

services:
  gg-konga:
    image: codejamninja/gg-konga:latest
    environment:
      OP_HOST: https://accounts.gluu.org/oxauth
    ports:
      - 1338:1338
    links:
      - gg-kong:kong
      - oxd-server:oxd
      - postgres:postgres

  gg-kong:
    image: codejamninja/gg-kong:latest
    ports:
      - 443:443
      - 8000:8000
    links:
      - postgres:postgres

  oxd-server:
    image: gluufederation/oxd-server:4.0
    environment:
      PROTECT_COMMANDS_WITH_ACCESS_TOKEN: 'true'
      DEFAULT_SITE_CONFIG_OP_HOST: https://accounts.gluu.org/oxauth

  postgres:
    image: postgres
