version: '3'

services:
  gg-kong:
    image: codejamninja/gg-kong:latest
    ports:
      - 443:443
      - 8000:8000
      - 8001:8001
    links:
      - postgres:postgres

  postgres:
    image: postgres
